curl -d '{  "first_name":"Lucas",  "last_name":"Hernanadez",  "uin":659982167,  "gpa":2.96,  "partner_first_name":"Chris",  "partner_last_name":"Dowd",  "partner_gpa":3.21,  "prefs":[1, 0, 4]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"BLucas",  "last_name":"BHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[3, 0, 2]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"CLucas",  "last_name":"CHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[5, 0, 0]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"DLucas",  "last_name":"DHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[1, 1, 3]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"ELucas",  "last_name":"EHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[0, 2, 3]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"FLucas",  "last_name":"FHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[1, 3, 1]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"GLucas",  "last_name":"GHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[2, 3, 0]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"HLucas",  "last_name":"HHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[0, 5, 0]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -d '{  "first_name":"ILucas",  "last_name":"IHernanadez",  "uin":659982168,  "gpa":2.96,  "partner_first_name":"BChris",  "partner_last_name":"BDowd",  "partner_gpa":3.21,  "prefs":[0, 0, 5]}'  -H "Content-Type: application/json" -X GET http://localhost:5000/StudentPreferenceData
curl -X GET http://localhost:5000/StudentList

curl -X GET http://localhost:5000/GA
